### ISSUE TITLE
Policy

### ISSUE THREAD

**Issue by ryan-mars** [stochastic/stochastic#10]
- [x] subscription filter for events #27
- [x] has an event handler lambda function
- [x] Handler can invoke commands #26 

 ### Policy 

<img width="826" alt="Software Model" src="https://user-images.githubusercontent.com/824046/117175460-800c8000-ad94-11eb-863e-d527af1bcd09.png">

_Illustrations ©️ Avanscoperta_

**Comment by sam-goodwin** [comment]
Is there a snippet from the event storming material we can include here, like we did for Bounded Context #7? I thought that was especially helpful.

**Comment by ryan-mars** [comment]
> Policies are probably the most interesting thing to model in EventStorming. They cover all the spectrum of organisation reactions from human behaviours to automation including:
> - habits
> - unconscious reactions
> - Tacit agreements
> - Explicit agreements
> - Codified or corporate rules
> - Inconsistent rules (different actors implementing the same rule in different ways)
> - Listeners (stateless listeners performing easy tasks, like sending notifications)
> - Process Managers and Sagas

> The link between an event and its consequences can be encapsulated by a policy, but when the event-reaction combination is too obvious, we might miss the link.
> Forcing ourself to obey the rule:
>  _**There has to be a lilac between the orange and the blue**_ 
> ...is a good way to force yourself into asking deeper questions about the nature of the policy.
