### ISSUE TITLE
BoundedContext: Public events are published to Event Bridge

### ISSUE THREAD

**Issue by ryan-mars** [stochastic/stochastic#28]
Epic: Bounded Context #7

Need a way to mark certain events as public and have the BoundedContext put those on the EventBridge bus.

**Comment by sam-goodwin** [comment]
Another advantage of shapes (#36) is that we can use the built-in json schema converter to generate the schemas for the registry.

**Comment by ryan-mars** [comment]
Yes, switching to Shapes can't happen soon enough.
