### ISSUE TITLE
Command: CommandResponse should return errors too

### ISSUE THREAD

**Issue by ryan-mars** [stochastic/stochastic#41]
Epic: Command #8

**Comment by sam-goodwin** [comment]
Should Errors be top-level objects, like `DomainEvent`, where they all have a fully qualified name and some Shape?

**Comment by ryan-mars** [comment]
> Should Errors be top-level objects, like `DomainEvent`, where they all have a fully qualified name and some Shape?

I don't see a need for Error to be a top level component, however `CommandResponse` should be a shape so it's easily serialized to JSON/schema. Error may need to be a Shape to facilitate this. 

JSON Schema of course makes it easer for legacy/non-stochastic systems to integrate with Stochastic to issue commands and generate SDK's. As a principle anything exposed outside the bounded context should have its messages (sent or received) published as JSON Schema.
